"""AREA_TAGS and SETPOINT_TARGETS for the Vla factory OPC-UA server.

GENERATED by tools/gen-connect.py from factory-model/isa95-vla.json.
Do not edit by hand: run the generator instead. `--check` fails the build
if this file and the model have drifted apart.
"""
from __future__ import annotations

from asyncua import ua

# (area, equipment) -> [(tag, VariantType, writable), ...]
AREA_TAGS: dict[tuple[str, str], list[tuple[str, ua.VariantType, bool]]] = {
    ("Receiving", "receiving-tank-01"): [
        ("level_L", ua.VariantType.Double, False),
        ("temp_C", ua.VariantType.Double, False),
        ("fat_setpoint_pct", ua.VariantType.Double, True),
    ],
    ("Mixing", "process-tank-01"): [
        ("level_L", ua.VariantType.Double, False),
        ("temp_C", ua.VariantType.Double, False),
        ("agitator_rpm", ua.VariantType.Double, True),
        ("dose_milk_actual_kg", ua.VariantType.Double, False),
        ("dose_sugar_actual_kg", ua.VariantType.Double, False),
        ("dose_starch_actual_kg", ua.VariantType.Double, False),
        ("dose_cocoa_actual_kg", ua.VariantType.Double, False),
        ("phase", ua.VariantType.String, False),
        ("dose_milk_setpoint_kg", ua.VariantType.Double, True),
        ("dose_sugar_setpoint_kg", ua.VariantType.Double, True),
        ("dose_starch_setpoint_kg", ua.VariantType.Double, True),
        ("dose_cocoa_setpoint_kg", ua.VariantType.Double, True),
    ],
    ("Cook", "cook-unit-01"): [
        ("temp_C", ua.VariantType.Double, False),
        ("setpoint_C", ua.VariantType.Double, True),
        ("hold_sec", ua.VariantType.Double, True),
        ("hold_elapsed_sec", ua.VariantType.Double, False),
        ("viscosity_cP", ua.VariantType.Double, False),
    ],
    ("Cooling", "cooler-01"): [
        ("temp_C", ua.VariantType.Double, False),
        ("target_C", ua.VariantType.Double, True),
    ],
    ("Filling", "filler-01"): [
        ("packs_total", ua.VariantType.Int64, False),
        ("reject_count", ua.VariantType.Int64, False),
        ("pack_size_L", ua.VariantType.Double, False),
    ],
}

# writable node -> the SetSetpoint target string it drives
SETPOINT_TARGETS: dict[tuple[str, str, str], str] = {
    ("Receiving", "receiving-tank-01", "fat_setpoint_pct"): "receiving.fat",
    ("Mixing", "process-tank-01", "agitator_rpm"): "mixing.agitator_rpm",
    ("Mixing", "process-tank-01", "dose_milk_setpoint_kg"): "dose.milk",
    ("Mixing", "process-tank-01", "dose_sugar_setpoint_kg"): "dose.sugar",
    ("Mixing", "process-tank-01", "dose_starch_setpoint_kg"): "dose.starch",
    ("Mixing", "process-tank-01", "dose_cocoa_setpoint_kg"): "dose.cocoa",
    ("Cook", "cook-unit-01", "setpoint_C"): "cook.setpoint_C",
    ("Cook", "cook-unit-01", "hold_sec"): "cook.hold_sec",
    ("Cooling", "cooler-01", "target_C"): "cooler.target_C",
}
