"""STATUS_TAGS / BATCH_TAGS / EQUIP_SETPOINT_TARGET for the fallback connector.

GENERATED by tools/gen-connect.py from factory-model/isa95-vla.json.
Do not edit by hand: run the generator instead. `--check` fails the build
if this file and the model have drifted apart.
"""
from __future__ import annotations

# (Area, Equipment, tag, unit)
STATUS_TAGS: list[tuple[str, str, str, str]] = [
    # Receiving
    ("Receiving", "receiving-tank-01", "level_L", "L"),
    ("Receiving", "receiving-tank-01", "temp_C", "C"),
    ("Receiving", "receiving-tank-01", "fat_setpoint_pct", "%"),
    # Mixing
    ("Mixing", "process-tank-01", "level_L", "L"),
    ("Mixing", "process-tank-01", "temp_C", "C"),
    ("Mixing", "process-tank-01", "agitator_rpm", "rpm"),
    ("Mixing", "process-tank-01", "dose_milk_actual_kg", "kg"),
    ("Mixing", "process-tank-01", "dose_sugar_actual_kg", "kg"),
    ("Mixing", "process-tank-01", "dose_starch_actual_kg", "kg"),
    ("Mixing", "process-tank-01", "dose_cocoa_actual_kg", "kg"),
    ("Mixing", "process-tank-01", "phase", ""),
    ("Mixing", "process-tank-01", "dose_milk_setpoint_kg", "kg"),
    ("Mixing", "process-tank-01", "dose_sugar_setpoint_kg", "kg"),
    ("Mixing", "process-tank-01", "dose_starch_setpoint_kg", "kg"),
    ("Mixing", "process-tank-01", "dose_cocoa_setpoint_kg", "kg"),
    # Cook
    ("Cook", "cook-unit-01", "temp_C", "C"),
    ("Cook", "cook-unit-01", "setpoint_C", "C"),
    ("Cook", "cook-unit-01", "hold_sec", "s"),
    ("Cook", "cook-unit-01", "hold_elapsed_sec", "s"),
    ("Cook", "cook-unit-01", "viscosity_cP", "cP"),
    # Cooling
    ("Cooling", "cooler-01", "temp_C", "C"),
    ("Cooling", "cooler-01", "target_C", "C"),
    # Filling
    ("Filling", "filler-01", "packs_total", ""),
    ("Filling", "filler-01", "reject_count", ""),
    ("Filling", "filler-01", "pack_size_L", "L"),
]

# (tag, unit) on the line-level Batch object
BATCH_TAGS: list[tuple[str, str]] = [
    ("state", ""),
    ("batch_id", ""),
    ("active_recipe", ""),
]

# equipment-level Command topic -> SetSetpoint target
# Keyed (Area, Equipment, tag): _route_equipment_command builds
# exactly that 3-tuple from the Command topic segments.
EQUIP_SETPOINT_TARGET: dict[tuple[str, str, str], str] = {
    ("Receiving", "receiving-tank-01", "fat_setpoint_pct"): "receiving.fat",
    ("Mixing", "process-tank-01", "agitator_rpm"): "mixing.agitator_rpm",
    ("Mixing", "process-tank-01", "dose_milk_setpoint_kg"): "dose.milk",
    ("Mixing", "process-tank-01", "dose_sugar_setpoint_kg"): "dose.sugar",
    ("Mixing", "process-tank-01", "dose_starch_setpoint_kg"): "dose.starch",
    ("Mixing", "process-tank-01", "dose_cocoa_setpoint_kg"): "dose.cocoa",
    ("Cook", "cook-unit-01", "setpoint_C"): "cook.setpoint_C",
    ("Cook", "cook-unit-01", "hold_sec"): "cook.hold_sec",
    ("Cooling", "cooler-01", "target_C"): "cooler.target_C",
}
