#!/bin/sh
# Register vendor island(s) as MonsterMQ OPC-UA device 'vendor-ua'.
#
# GENERATED by tools/gen-connect.py from factory-model/source-systems.json.
# Do not edit by hand: edit the model and run the generator.
#
# Islands on this device: homogeniser-01, cip-station-01
# Endpoint: opc.tcp://vla-vendor-opcua:4842/VendorLine  (ns=2)
#
# Raw data lands on raw/vla/<equipment>/<native-item>, deliberately
# OUTSIDE the DairyWorks/ UNS tree: archive group 'dairyworks_data' matches
# DairyWorks/# and would silently archive every unmodelled vendor tag. Raw is
# not stored anywhere until the Condition and Model steps have made it mean
# something.
#
# NOTE the payload MonsterMQ emits here is {value, timestamp, status}, which
# is NOT the UNS contract {value, unit, ts, quality}. Different key names, no
# unit at all, and a numeric OPC-UA StatusCode where the contract wants
# GOOD/BAD/UNCERTAIN. That mismatch is structural, not an oversight.

GQL="http://monstermq:4000/graphql"
NS="ns=2"
DEVICE="vendor-ua"

echo "[$DEVICE-init] Waiting for MonsterMQ..."
until curl -sf "http://monstermq:4000/" > /dev/null 2>&1; do sleep 3; done

gql() {
  curl -sf -X POST "$GQL" -H "Content-Type: application/json" \
    -d "{\"query\":\"$1\"}"
}

# Idempotent: config persists in Mongo, so a redeploy must not duplicate.
EXISTS=$(gql "{opcUaDevices{name}}")
case "$EXISTS" in
  *'"vendor-ua"'*)
    echo "[$DEVICE-init] device 'vendor-ua' already registered, skipping."
    exit 0 ;;
esac

ADD=$(gql "mutation{opcUaDevice{add(input:{name:\\\"vendor-ua\\\",namespace:\\\"raw/vla\\\",nodeId:\\\"local\\\",enabled:true,config:{endpointUrl:\\\"opc.tcp://vla-vendor-opcua:4842/VendorLine\\\",securityPolicy:None,subscriptionSamplingInterval:1000.0}}){success errors}}}")
echo "[$DEVICE-init] add: $ADD"
case "$ADD" in
  *'"success":true'*) : ;;
  *) echo "[$DEVICE-init] WARN: opcUaDevice.add failed"; exit 1 ;;
esac

# BEGIN GENERATED TAGS (tools/gen-connect.py), do not edit by hand
TAGS="
PT_1101_PV|homogeniser-01/PT_1101_PV
PT_1102_PV|homogeniser-01/PT_1102_PV
MTR_1101_SPD|homogeniser-01/MTR_1101_SPD
MTR_1101_LOAD|homogeniser-01/MTR_1101_LOAD
TT_1103_PV|homogeniser-01/TT_1103_PV
STS_1101|homogeniser-01/STS_1101
CIP1.Phase|cip-station-01/CIP1.Phase
CIP1.Cond_mS|cip-station-01/CIP1.Cond_mS
CIP1.SupplyTemp_C|cip-station-01/CIP1.SupplyTemp_C
CIP1.ReturnTemp_C|cip-station-01/CIP1.ReturnTemp_C
CIP1.Flow_m3h|cip-station-01/CIP1.Flow_m3h
CIP1.ElapsedMin|cip-station-01/CIP1.ElapsedMin
"
# END GENERATED TAGS

OK=0; FAIL=0
for LINE in $TAGS; do
  NODE=${LINE%%|*}
  TOPIC=${LINE##*|}
  RES=$(gql "mutation{opcUaDevice{addAddress(deviceName:\\\"vendor-ua\\\",input:{address:\\\"NodeId://$NS;s=$NODE\\\",topic:\\\"$TOPIC\\\",publishMode:SEPARATE}){success errors}}}")
  case "$RES" in
    *'"success":true'*) OK=$((OK+1)) ;;
    *) FAIL=$((FAIL+1)); echo "[$DEVICE-init] WARN addAddress $NODE -> $RES" ;;
  esac
done

echo "[$DEVICE-init] $OK addresses OK, $FAIL failed."
[ "$FAIL" -gt 0 ] && exit 1
echo "[$DEVICE-init] Done. Raw vendor data flows to raw/vla/#"
