#!/bin/sh
# Register vendor island(s) as MonsterMQ OPC-UA device 'vendor-da'.
#
# GENERATED by tools/gen-connect.py from factory-model/source-systems.json.
# Do not edit by hand: edit the model and run the generator.
#
# Islands on this device: pasteuriser-01
# Endpoint: opc.tcp://vla-vendor-opcda:4843/DATunnel  (ns=2)
#
# Raw data lands on raw/vla/<equipment>/<native-item>, deliberately
# OUTSIDE the DairyWorks/ UNS tree: archive group 'dairyworks_data' matches
# DairyWorks/# and would silently archive every unmodelled vendor tag. Raw is
# not stored anywhere until the Condition and Model steps have made it mean
# something.
#
# NOTE the payload MonsterMQ emits here is {value, timestamp, status}, which
# is NOT the UNS contract {value, unit, ts, quality}. Different key names, no
# unit at all, and a numeric OPC-UA StatusCode where the contract wants
# GOOD/BAD/UNCERTAIN. That mismatch is structural, not an oversight.

GQL="http://monstermq:4000/graphql"
NS="ns=2"
DEVICE="vendor-da"

echo "[$DEVICE-init] Waiting for MonsterMQ..."
until curl -sf "http://monstermq:4000/" > /dev/null 2>&1; do sleep 3; done

gql() {
  curl -sf -X POST "$GQL" -H "Content-Type: application/json" \
    -d "{\"query\":\"$1\"}"
}

# Idempotent: config persists in Mongo, so a redeploy must not duplicate.
EXISTS=$(gql "{opcUaDevices{name}}")
case "$EXISTS" in
  *'"vendor-da"'*)
    echo "[$DEVICE-init] device 'vendor-da' already registered, skipping."
    exit 0 ;;
esac

ADD=$(gql "mutation{opcUaDevice{add(input:{name:\\\"vendor-da\\\",namespace:\\\"raw/vla\\\",nodeId:\\\"local\\\",enabled:true,config:{endpointUrl:\\\"opc.tcp://vla-vendor-opcda:4843/DATunnel\\\",securityPolicy:None,subscriptionSamplingInterval:1000.0}}){success errors}}}")
echo "[$DEVICE-init] add: $ADD"
case "$ADD" in
  *'"success":true'*) : ;;
  *) echo "[$DEVICE-init] WARN: opcUaDevice.add failed"; exit 1 ;;
esac

# BEGIN GENERATED TAGS (tools/gen-connect.py), do not edit by hand
TAGS="
Ch1.Dev2.TT_3001_PV|pasteuriser-01/Ch1.Dev2.TT_3001_PV
Ch1.Dev2.TT_3001_PV.Q|pasteuriser-01/Ch1.Dev2.TT_3001_PV.Q
Ch1.Dev2.TT_3002_PV|pasteuriser-01/Ch1.Dev2.TT_3002_PV
Ch1.Dev2.TT_3002_PV.Q|pasteuriser-01/Ch1.Dev2.TT_3002_PV.Q
Ch1.Dev2.TT_3003_PV|pasteuriser-01/Ch1.Dev2.TT_3003_PV
Ch1.Dev2.TT_3003_PV.Q|pasteuriser-01/Ch1.Dev2.TT_3003_PV.Q
Ch1.Dev2.ZV_3004_ST|pasteuriser-01/Ch1.Dev2.ZV_3004_ST
Ch1.Dev2.ZV_3004_ST.Q|pasteuriser-01/Ch1.Dev2.ZV_3004_ST.Q
Ch1.Dev2.FT_3006_PV|pasteuriser-01/Ch1.Dev2.FT_3006_PV
Ch1.Dev2.FT_3006_PV.Q|pasteuriser-01/Ch1.Dev2.FT_3006_PV.Q
"
# END GENERATED TAGS

OK=0; FAIL=0
for LINE in $TAGS; do
  NODE=${LINE%%|*}
  TOPIC=${LINE##*|}
  RES=$(gql "mutation{opcUaDevice{addAddress(deviceName:\\\"vendor-da\\\",input:{address:\\\"NodeId://$NS;s=$NODE\\\",topic:\\\"$TOPIC\\\",publishMode:SEPARATE}){success errors}}}")
  case "$RES" in
    *'"success":true'*) OK=$((OK+1)) ;;
    *) FAIL=$((FAIL+1)); echo "[$DEVICE-init] WARN addAddress $NODE -> $RES" ;;
  esac
done

echo "[$DEVICE-init] $OK addresses OK, $FAIL failed."
[ "$FAIL" -gt 0 ] && exit 1
echo "[$DEVICE-init] Done. Raw vendor data flows to raw/vla/#"
