#!/usr/bin/env python3
"""gen-connect.py: generate every connect artefact from the ISA-95 model.

WHY THIS EXISTS
---------------
The Vla tag table used to live in FOUR hand-maintained copies:

  1. factory/server.py           AREA_TAGS          (the OPC-UA address space)
  2. factory-model/isa95-vla.json                   (the ISA-95 model)
  3. monstermq-init/init-vla-opcua.sh               (the MonsterMQ ingest list)
  4. connector/connector.py      STATUS_TAGS        (the fallback bridge)

They drifted. The four `dose_*_setpoint_kg` tags existed in (1) and (2) but were
absent from (3) and (4), so they never reached the UNS at all. That is not a
cosmetic bug: per the field-name canon (06-Model B.2b) a target and its actual
"bestaan altijd als PAAR", and a consumer judging dose quality compares the
pair. Half the pair was invisible.

Four copies drifted at 25 tags. The vendor-island extension adds ~57 more. So
this generator is a hard gate: `isa95-vla.json` is the single source of truth,
and (1), (3) and (4) are generated from it.

WHAT IS NOT DONE, DELIBERATELY
------------------------------
`factory/server.py` does NOT read the model at runtime, even though the
container already receives FACTORY_MODEL and that looks like the obvious fix.
Three reasons:
  * vla-factory is the simulated PLC. A real PLC does not read the enterprise
    ISA-95 model at boot. Making it do so blurs exactly the OT/IT boundary the
    whole demo argues about.
  * It adds a new failure surface to the one container nothing else can survive.
  * It breaks offline-first: the factory would stop booting without a model file.

Build-time generation gives the same single source of truth with none of the
runtime coupling.

USAGE
-----
    python tools/gen-connect.py            # write the generated files
    python tools/gen-connect.py --check    # verify they are up to date (CI/deploy)

--check is pure file I/O and string comparison: no broker, no Mongo, no network,
so it is safe in any offline context.
"""
from __future__ import annotations

import argparse
import json
import sys
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODEL = ROOT / "factory-model" / "isa95-vla.json"
SOURCES = ROOT / "factory-model" / "source-systems.json"

BEGIN = "# BEGIN GENERATED TAGS (tools/gen-connect.py), do not edit by hand"
END = "# END GENERATED TAGS"

BANNER = (
    "GENERATED by tools/gen-connect.py from factory-model/isa95-vla.json.\n"
    "Do not edit by hand: run the generator instead. `--check` fails the build\n"
    "if this file and the model have drifted apart."
)

# Model engineering_unit -> the unit string published on the wire.
# The model carries display units; the UNS payload carries terse ones, and
# `vla/bus.py` plus the UI already read those. This map keeps the generated
# output byte-identical in behaviour to the hand-written table it replaces,
# so Phase 0 is a pure de-drift with no consumer-visible change.
WIRE_UNIT = {
    "°C": "C",
    "enum": "",
    "id": "",
    "count": "",
}

# Model opcua_datatype -> asyncua VariantType attribute name.
VARIANT = {
    "Double": "Double",
    "Int64": "Int64",
    "String": "String",
}


class Tag:
    __slots__ = ("area", "equipment", "name", "datatype", "unit", "writable", "command_target")

    def __init__(self, area, equipment, name, datatype, unit, writable, command_target):
        self.area = area
        self.equipment = equipment
        self.name = name
        self.datatype = datatype
        self.unit = unit
        self.writable = writable
        self.command_target = command_target

    @property
    def wire_unit(self) -> str:
        return WIRE_UNIT.get(self.unit, self.unit)

    @property
    def node_suffix(self) -> str:
        """The part after `DairyWorks.Vla.` in the OPC-UA NodeId string."""
        if self.area is None:  # line-level Batch object
            return f"Batch.{self.name}"
        return f"{self.area}.{self.equipment}.{self.name}"

    @property
    def topic_suffix(self) -> str:
        """The per-address topic; MonsterMQ prefixes the device namespace."""
        if self.area is None:
            return f"Batch/Status/{self.name}"
        return f"{self.area}/{self.equipment}/Status/{self.name}"


def load_tags(model: dict) -> tuple[list[Tag], list[Tag]]:
    """Return (equipment_tags, batch_tags) in model order.

    Model order is load-bearing: it keeps the generated diffs readable and the
    OPC-UA browse order stable between runs.
    """
    line = model["enterprise"]["sites"][0]["lines"][0]
    equipment: list[Tag] = []
    for area in line["areas"]:
        for wc in area["work_centers"]:
            eq = wc["equipment_id"]
            for t in wc["tags"]:
                tag_eq, tag_name = t["id"].split(":", 1)
                if tag_eq != eq:
                    raise SystemExit(
                        f"model inconsistency: tag id {t['id']!r} does not match "
                        f"equipment_id {eq!r} in work_center {wc['id']!r}"
                    )
                equipment.append(Tag(
                    area=area["name"],
                    equipment=eq,
                    name=tag_name,
                    datatype=t["opcua_datatype"],
                    unit=t["engineering_unit"],
                    writable=bool(t.get("writable")),
                    command_target=t.get("command_target"),
                ))
    batch: list[Tag] = []
    for t in line["batch_object"]["tags"]:
        _, tag_name = t["id"].split(":", 1)
        batch.append(Tag(
            area=None,
            equipment="Batch",
            name=tag_name,
            datatype=t["opcua_datatype"],
            unit=t["engineering_unit"],
            writable=bool(t.get("writable")),
            command_target=t.get("command_target"),
        ))
    return equipment, batch


# ---------------------------------------------------------------------------
# 1. factory/_generated_tags.py: the OPC-UA address space
# ---------------------------------------------------------------------------

def render_factory(equipment: list[Tag]) -> str:
    out: list[str] = [
        '"""AREA_TAGS and SETPOINT_TARGETS for the Vla factory OPC-UA server.',
        "",
    ]
    out += [BANNER, '"""', "from __future__ import annotations", "",
            "from asyncua import ua", "",
            "# (area, equipment) -> [(tag, VariantType, writable), ...]",
            "AREA_TAGS: dict[tuple[str, str], list[tuple[str, ua.VariantType, bool]]] = {"]

    seen: list[tuple[str, str]] = []
    for t in equipment:
        key = (t.area, t.equipment)
        if key not in seen:
            if seen:
                out.append("    ],")
            out.append(f'    ("{t.area}", "{t.equipment}"): [')
            seen.append(key)
        out.append(
            f'        ("{t.name}", ua.VariantType.{VARIANT[t.datatype]}, {t.writable}),'
        )
    if seen:
        out.append("    ],")
    out.append("}")
    out.append("")
    out.append("# writable node -> the SetSetpoint target string it drives")
    out.append("SETPOINT_TARGETS: dict[tuple[str, str, str], str] = {")
    for t in equipment:
        if t.command_target:
            out.append(
                f'    ("{t.area}", "{t.equipment}", "{t.name}"): "{t.command_target}",'
            )
    out.append("}")
    out.append("")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 2. connector/_generated_tags.py: the fallback bridge tables
# ---------------------------------------------------------------------------

def render_connector(equipment: list[Tag], batch: list[Tag]) -> str:
    out = ['"""STATUS_TAGS / BATCH_TAGS / EQUIP_SETPOINT_TARGET for the fallback connector.',
           "", BANNER, '"""', "from __future__ import annotations", "",
           "# (Area, Equipment, tag, unit)",
           "STATUS_TAGS: list[tuple[str, str, str, str]] = ["]
    current = None
    for t in equipment:
        if t.area != current:
            out.append(f"    # {t.area}")
            current = t.area
        out.append(
            f'    ("{t.area}", "{t.equipment}", "{t.name}", "{t.wire_unit}"),'
        )
    out.append("]")
    out.append("")
    out.append("# (tag, unit) on the line-level Batch object")
    out.append("BATCH_TAGS: list[tuple[str, str]] = [")
    for t in batch:
        out.append(f'    ("{t.name}", "{t.wire_unit}"),')
    out.append("]")
    out.append("")
    out.append("# equipment-level Command topic -> SetSetpoint target")
    out.append("# Keyed (Area, Equipment, tag): _route_equipment_command builds")
    out.append("# exactly that 3-tuple from the Command topic segments.")
    out.append("EQUIP_SETPOINT_TARGET: dict[tuple[str, str, str], str] = {")
    for t in equipment:
        if t.command_target:
            out.append(
                f'    ("{t.area}", "{t.equipment}", "{t.name}"): "{t.command_target}",'
            )
    out.append("}")
    out.append("")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 3. monstermq-init/init-vla-opcua.sh: only the TAGS block, between markers
# ---------------------------------------------------------------------------

def render_init_tags(equipment: list[Tag], batch: list[Tag]) -> str:
    lines = [BEGIN, 'TAGS="']
    for t in equipment + batch:
        lines.append(f"{t.node_suffix}|{t.topic_suffix}")
    lines.append('"')
    lines.append(END)
    return "\n".join(lines)


def splice(path: Path, block: str) -> str:
    """Replace the region between BEGIN/END markers, keeping everything else."""
    text = path.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        raise SystemExit(
            f"{path.relative_to(ROOT)} has no generated-block markers. Add:\n"
            f"  {BEGIN}\n  ...\n  {END}"
        )
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return head + block + tail


# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# 4. monstermq-init/init-vendor-*.sh: one MonsterMQ device per vendor island
# ---------------------------------------------------------------------------

def render_vendor_init(device: str, systems: list[dict], raw_root: str) -> str:
    """A full init script for one MonsterMQ OPC-UA device covering N islands.

    Generated whole rather than spliced, because every value in it (endpoint,
    namespace index, address list) comes from source-systems.json. There is no
    hand-written half to protect.
    """
    endpoint = systems[0]["endpoint"]
    ns_index = systems[0]["opcua_namespace_index"]
    equip = ", ".join(s["equipment_id"] for s in systems)

    addresses: list[tuple[str, str]] = []
    for s in systems:
        prefix = s["raw_prefix"]
        for p in s["points"]:
            native = p["native"]
            addresses.append((native, f"{prefix}/{native}"))
            # Only a DA island carries its quality as a SEPARATE item. On a
            # modern UA server the quality is the StatusCode on the value
            # itself, so asking for a .Q node there requests something that
            # does not exist: 12 addresses that can never read.
            if s.get("native_quality") == "da-quality-word":
                addresses.append((f"{native}.Q", f"{prefix}/{native}.Q"))

    out = [
        "#!/bin/sh",
        f"# Register vendor island(s) as MonsterMQ OPC-UA device '{device}'.",
        "#",
        f"# GENERATED by tools/gen-connect.py from factory-model/source-systems.json.",
        "# Do not edit by hand: edit the model and run the generator.",
        "#",
        f"# Islands on this device: {equip}",
        f"# Endpoint: {endpoint}  (ns={ns_index})",
        "#",
        f"# Raw data lands on {raw_root}/<equipment>/<native-item>, deliberately",
        "# OUTSIDE the DairyWorks/ UNS tree: archive group 'dairyworks_data' matches",
        "# DairyWorks/# and would silently archive every unmodelled vendor tag. Raw is",
        "# not stored anywhere until the Condition and Model steps have made it mean",
        "# something.",
        "#",
        "# NOTE the payload MonsterMQ emits here is {value, timestamp, status}, which",
        "# is NOT the UNS contract {value, unit, ts, quality}. Different key names, no",
        "# unit at all, and a numeric OPC-UA StatusCode where the contract wants",
        "# GOOD/BAD/UNCERTAIN. That mismatch is structural, not an oversight.",
        "",
        'GQL="http://monstermq:4000/graphql"',
        f'NS="ns={ns_index}"',
        f'DEVICE="{device}"',
        "",
        'echo "[$DEVICE-init] Waiting for MonsterMQ..."',
        'until curl -sf "http://monstermq:4000/" > /dev/null 2>&1; do sleep 3; done',
        "",
        "gql() {",
        '  curl -sf -X POST "$GQL" -H "Content-Type: application/json" \\',
        '    -d "{\\"query\\":\\"$1\\"}"',
        "}",
        "",
        "# Idempotent: config persists in Mongo, so a redeploy must not duplicate.",
        'EXISTS=$(gql "{opcUaDevices{name}}")',
        'case "$EXISTS" in',
        f'  *\'"{device}"\'*)',
        f'    echo "[$DEVICE-init] device \'{device}\' already registered, skipping."',
        "    exit 0 ;;",
        "esac",
        "",
        f'ADD=$(gql "mutation{{opcUaDevice{{add(input:{{name:\\\\\\"{device}\\\\\\",'
        f'namespace:\\\\\\"{raw_root}\\\\\\",nodeId:\\\\\\"local\\\\\\",enabled:true,'
        f'config:{{endpointUrl:\\\\\\"{endpoint}\\\\\\",securityPolicy:None,'
        f'subscriptionSamplingInterval:1000.0}}}}){{success errors}}}}}}")',
        'echo "[$DEVICE-init] add: $ADD"',
        'case "$ADD" in',
        "  *'\"success\":true'*) : ;;",
        '  *) echo "[$DEVICE-init] WARN: opcUaDevice.add failed"; exit 1 ;;',
        "esac",
        "",
        "# BEGIN GENERATED TAGS (tools/gen-connect.py), do not edit by hand",
        'TAGS="',
    ]
    out += [f"{node}|{topic}" for node, topic in addresses]
    out += [
        '"',
        "# END GENERATED TAGS",
        "",
        "OK=0; FAIL=0",
        "for LINE in $TAGS; do",
        "  NODE=${LINE%%|*}",
        "  TOPIC=${LINE##*|}",
        '  RES=$(gql "mutation{opcUaDevice{addAddress(deviceName:\\\\\\"'
        + device
        + '\\\\\\",input:{address:\\\\\\"NodeId://$NS;s=$NODE\\\\\\",'
        'topic:\\\\\\"$TOPIC\\\\\\",publishMode:SEPARATE}){success errors}}}")',
        "  case \"$RES\" in",
        "    *'\"success\":true'*) OK=$((OK+1)) ;;",
        '    *) FAIL=$((FAIL+1)); echo "[$DEVICE-init] WARN addAddress $NODE -> $RES" ;;',
        "  esac",
        "done",
        "",
        'echo "[$DEVICE-init] $OK addresses OK, $FAIL failed."',
        '[ "$FAIL" -gt 0 ] && exit 1',
        f'echo "[$DEVICE-init] Done. Raw vendor data flows to {raw_root}/#"',
        "",
    ]
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 5. factory-model/aliases.json + conditioning.json: the Model and Condition
#    tables. Generated, because every fact they need is already declared on the
#    points in source-systems.json and a fifth hand-kept copy is exactly what
#    this generator exists to prevent.
# ---------------------------------------------------------------------------

# Fixed namespace for uuid5. Never change it: every canonical_signal_uuid in
# every historian row is derived from it.
UUID_NS = uuid.UUID("6f1f4a1e-6b6a-4a6e-9a1c-4d2f8e5b1c00")

# canonical tag suffix -> canonical unit. Same house convention as the sims
# (06-Model B.2b: the unit is a suffix on the tag name).
CANON_UNIT = {
    "_C": "C", "_L_min": "L/min", "_m3_h": "m3/h", "_kg": "kg", "_bar": "bar",
    "_pct": "%", "_rpm": "rpm", "_sec": "s", "_min": "min", "_cP": "cP",
    "_mS": "mS", "_L": "L", "_g": "g",
}


def canon_unit(tag_id: str) -> str:
    tag = tag_id.split(":", 1)[1]
    for suffix, unit in sorted(CANON_UNIT.items(), key=lambda kv: -len(kv[0])):
        if tag.endswith(suffix):
            return unit
    return ""


def area_index(doc: dict) -> dict[str, str]:
    """equipment_id -> Area, across BOTH the line PLC and the vendor systems.

    A lab system reports a measurement ABOUT another asset, so its canonical tag
    belongs to that asset's Area, not to the lab's. Filing lims-01's fat reading
    under Utilities would keep it apart from the setpoint it is supposed to pair
    with, which is the exact bug the pair rule exists to prevent.
    """
    idx: dict[str, str] = {}
    model = json.loads(MODEL.read_text(encoding="utf-8"))
    line = model["enterprise"]["sites"][0]["lines"][0]
    for area in line["areas"]:
        for wc in area["work_centers"]:
            idx[wc["equipment_id"]] = area["name"]
    for s in doc["source_systems"]:
        idx.setdefault(s["equipment_id"], s["area"])
    return idx


def _iter_points(doc: dict):
    for s in doc["source_systems"]:
        if not s.get("enabled", True):
            continue
        for p in s["points"]:
            yield s, p


def raw_topic_for(doc: dict, system: dict, point: dict) -> str:
    return f"{doc['raw_root']}/{system['raw_prefix']}/{point['native']}"


def render_aliases(doc: dict) -> str:
    """The Model table: native name -> stable identity -> canonical UNS topic."""
    aliases = []
    areas = area_index(doc)
    for s, p in _iter_points(doc):
        tag_id = p["canonical_tag_id"]
        equipment, tag = tag_id.split(":", 1)
        area = areas.get(equipment, s["area"])
        aliases.append({
            "legacy_tag": raw_topic_for(doc, s, p),
            # uuid5, so the identity is reproducible from the canonical tag id and
            # survives the VENDOR renaming its item. That is the whole point: the
            # historian keeps one series when the field name changes underneath.
            "canonical_signal_uuid": str(uuid.uuid5(UUID_NS, tag_id)),
            "canonical_topic": f"DairyWorks/Vla/{area}/{equipment}/Status/{tag}",
            "canonical_tag_id": tag_id,
            "canonical_unit": canon_unit(tag_id),
            "source_system": s["id"],
            "equipment_id": equipment,
            "vendor": s["vendor"],
            "native_name": p["native"],
            "native_unit": p.get("native_unit", ""),
            "condition_rule": p["condition_rule"],
            "retired_at": p.get("retired_at"),
        })
    doc_out = {
        "schema_version": "1.0",
        "_generated": BANNER.replace("\n", " "),
        "mirrors": "warehouse.tag_aliases, see idp-os/docs/data-modeling.md",
        "note": [
            "This is the Model step. It is the difference between a number and a fact.",
            "",
            "canonical_signal_uuid is the stable identity. It is derived from the",
            "canonical tag id, NOT from the vendor's name, so when a vendor renames",
            "TT_3003_PV the alias row changes and the identity does not. Downstream",
            "keeps one continuous series instead of silently starting a new one.",
            "",
            "retired_at set means the alias still RESOLVES on read but no longer",
            "PUBLISHES. That is what makes an upstream rename a non-event."
        ],
        "aliases": aliases,
    }
    return json.dumps(doc_out, indent=2, ensure_ascii=False) + "\n"


def render_conditioning(doc: dict) -> str:
    """The Condition table: what must happen to the value before it means anything."""
    rules = {}
    for s, p in _iter_points(doc):
        tag_id = p["canonical_tag_id"]
        rule = {
            "native_unit": p.get("native_unit", ""),
            "canonical_unit": canon_unit(tag_id),
            # A register holding tenths is multiplied by 0.1 to become engineering
            # units. Nothing in the payload says so, which is why this table exists.
            "scale": float(p.get("native_scale", 1) or 1),
            "quality_source": s.get("native_quality", "none"),
            "timestamp_source": s.get("native_timestamp", "none"),
            "expected_interval_s": s.get("expected_interval_s", 60),
        }
        if p.get("deadband") is not None:
            rule["deadband"] = p["deadband"]
        if p.get("display_decimals") is not None:
            rule["display_decimals"] = p["display_decimals"]
        rules[p["condition_rule"]] = rule
    doc_out = {
        "schema_version": "1.0",
        "_generated": BANNER.replace("\n", " "),
        "note": [
            "One rule per point, keyed by condition_rule so several points can share",
            "one. Config, not code: a conversion you cannot see in a git diff is a",
            "conversion you cannot audit, and in food production audit is the point.",
            "",
            "stale_threshold_s comes from isa95-vla.json so there is one number, and",
            "deadband exists because agitator_rpm once produced 5.34 of the",
            "historian's 5.35 million rows (factory/server.py)."
        ],
        "defaults": {
            "assume_tz": "Europe/Amsterdam",
            "deadband": 0.0,
            "quality_map": {
                "da-quality-word": {"192": "GOOD", "64": "UNCERTAIN", "0": "BAD"},
                "opcua-statuscode": {"0": "GOOD", "_bad_prefix": "BAD", "_uncertain_prefix": "UNCERTAIN"},
                "none": {"_default": "GOOD"}
            }
        },
        "rules": rules,
    }
    return json.dumps(doc_out, indent=2, ensure_ascii=False) + "\n"


def model_targets() -> dict[Path, str]:
    if not SOURCES.exists():
        return {}
    doc = json.loads(SOURCES.read_text(encoding="utf-8"))
    return {
        ROOT / "factory-model" / "aliases.json": render_aliases(doc),
        ROOT / "factory-model" / "conditioning.json": render_conditioning(doc),
    }


def render_gateway_sources(doc: dict) -> str:
    """vendor-gateway/sources.yaml: the SQL islands MonsterMQ cannot reach itself."""
    out = [
        "# GENERATED by tools/gen-connect.py from factory-model/source-systems.json.",
        "# Do not edit by hand: edit the model and run the generator.",
        "#",
        "# MonsterMQ has no SQL source connector (its device list is opcUaDevice,",
        "# opcUaServer, mqttClient, kafkaClient, winCCOa/Ua, plc4x, nats, redis,",
        "# telegram, neo4j, sparkplugBDecoder; the loggers are sinks). So the",
        "# gateway polls these and publishes onto the same raw root as everything",
        "# else, which keeps the Condition and Model steps unaware of the protocol.",
        "",
        f"raw_root: {doc['raw_root']}",
        "sources:",
    ]
    for s in doc["source_systems"]:
        if s.get("ingest") != "gateway-sql" or not s.get("enabled", True):
            continue
        out += [
            f"  - id: {s['id']}",
            f"    equipment_id: {s['equipment_id']}",
            f"    raw_prefix: {s['raw_prefix']}",
            "    type: mssql",
            f"    endpoint: {s['endpoint']}",
            f"    poll_s: {s.get('expected_interval_s', 60)}",
            f"    table: {s['table']}",
            f"    query: >-",
            f"      {s['query']}",
            f"    watermark: {s['watermark'] or 'null'}",
            f"    key_columns: [{', '.join(s['key_columns'])}]",
            f"    value_column: {s['value_column']}",
            f"    native_timestamp: {s.get('native_timestamp', 'none')}",
            "    points:",
        ]
        for p in s["points"]:
            out.append(f"      - native: \"{p['native']}\"")
            out.append(f"        canonical_tag_id: {p['canonical_tag_id']}")
    out.append("")
    return "\n".join(out)


def vendor_targets() -> dict[Path, str]:
    """Init scripts for every MonsterMQ-ingested vendor island, grouped by device."""
    if not SOURCES.exists():
        return {}
    doc = json.loads(SOURCES.read_text(encoding="utf-8"))
    raw_root = doc["raw_root"]
    by_device: dict[str, list[dict]] = {}
    for s in doc["source_systems"]:
        if not s.get("enabled", True):
            continue
        if s.get("ingest") != "monstermq-opcua":
            continue  # gateway-ingested sources are configured in sources.yaml
        by_device.setdefault(s["device_name"], []).append(s)

    out: dict[Path, str] = {}
    for device, systems in sorted(by_device.items()):
        path = ROOT / "monstermq-init" / f"init-{device}.sh"
        out[path] = render_vendor_init(device, systems, raw_root)
    if any(s.get("ingest") == "gateway-sql" for s in doc["source_systems"]):
        out[ROOT / "vendor-gateway" / "sources.yaml"] = render_gateway_sources(doc)
    return out


def targets(model: dict) -> dict[Path, str]:
    equipment, batch = load_tags(model)
    init_path = ROOT / "monstermq-init" / "init-vla-opcua.sh"
    out = {
        ROOT / "factory" / "_generated_tags.py": render_factory(equipment),
        ROOT / "connector" / "_generated_tags.py": render_connector(equipment, batch),
        init_path: splice(init_path, render_init_tags(equipment, batch)),
    }
    out.update(vendor_targets())
    out.update(model_targets())
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="fail if a generated file is out of date; write nothing")
    args = ap.parse_args()

    if not MODEL.exists():
        print(f"[gen-connect] model not found: {MODEL}", file=sys.stderr)
        return 2
    model = json.loads(MODEL.read_text(encoding="utf-8"))

    equipment, batch = load_tags(model)
    wanted = targets(model)

    stale: list[str] = []
    for path, content in wanted.items():
        rel = path.relative_to(ROOT)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(str(rel))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"[gen-connect] wrote {rel}")

    if args.check:
        if stale:
            print("[gen-connect] OUT OF DATE: " + ", ".join(stale), file=sys.stderr)
            print("[gen-connect] run: python tools/gen-connect.py", file=sys.stderr)
            return 1
        print(f"[gen-connect] CHECK OK: {len(equipment)} equipment tags + "
              f"{len(batch)} batch tags, {len(wanted)} artefacts in sync")
        return 0

    print(f"[gen-connect] done: {len(equipment)} equipment tags + {len(batch)} "
          f"batch tags -> {len(equipment) + len(batch)} MonsterMQ addresses")
    return 0


if __name__ == "__main__":
    sys.exit(main())
