#!/usr/bin/env python3
"""gen-connect.py: generate every connect artefact from the ISA-95 model.

WHY THIS EXISTS
---------------
The Vla tag table used to live in FOUR hand-maintained copies:

  1. factory/server.py           AREA_TAGS          (the OPC-UA address space)
  2. factory-model/isa95-vla.json                   (the ISA-95 model)
  3. monstermq-init/init-vla-opcua.sh               (the MonsterMQ ingest list)
  4. connector/connector.py      STATUS_TAGS        (the fallback bridge)

They drifted. The four `dose_*_setpoint_kg` tags existed in (1) and (2) but were
absent from (3) and (4), so they never reached the UNS at all. That is not a
cosmetic bug: per the field-name canon (06-Model B.2b) a target and its actual
"bestaan altijd als PAAR", and a consumer judging dose quality compares the
pair. Half the pair was invisible.

Four copies drifted at 25 tags. The vendor-island extension adds ~57 more. So
this generator is a hard gate: `isa95-vla.json` is the single source of truth,
and (1), (3) and (4) are generated from it.

WHAT IS NOT DONE, DELIBERATELY
------------------------------
`factory/server.py` does NOT read the model at runtime, even though the
container already receives FACTORY_MODEL and that looks like the obvious fix.
Three reasons:
  * vla-factory is the simulated PLC. A real PLC does not read the enterprise
    ISA-95 model at boot. Making it do so blurs exactly the OT/IT boundary the
    whole demo argues about.
  * It adds a new failure surface to the one container nothing else can survive.
  * It breaks offline-first: the factory would stop booting without a model file.

Build-time generation gives the same single source of truth with none of the
runtime coupling.

USAGE
-----
    python tools/gen-connect.py            # write the generated files
    python tools/gen-connect.py --check    # verify they are up to date (CI/deploy)

--check is pure file I/O and string comparison: no broker, no Mongo, no network,
so it is safe in any offline context.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODEL = ROOT / "factory-model" / "isa95-vla.json"

BEGIN = "# BEGIN GENERATED TAGS (tools/gen-connect.py), do not edit by hand"
END = "# END GENERATED TAGS"

BANNER = (
    "GENERATED by tools/gen-connect.py from factory-model/isa95-vla.json.\n"
    "Do not edit by hand: run the generator instead. `--check` fails the build\n"
    "if this file and the model have drifted apart."
)

# Model engineering_unit -> the unit string published on the wire.
# The model carries display units; the UNS payload carries terse ones, and
# `vla/bus.py` plus the UI already read those. This map keeps the generated
# output byte-identical in behaviour to the hand-written table it replaces,
# so Phase 0 is a pure de-drift with no consumer-visible change.
WIRE_UNIT = {
    "°C": "C",
    "enum": "",
    "id": "",
    "count": "",
}

# Model opcua_datatype -> asyncua VariantType attribute name.
VARIANT = {
    "Double": "Double",
    "Int64": "Int64",
    "String": "String",
}


class Tag:
    __slots__ = ("area", "equipment", "name", "datatype", "unit", "writable", "command_target")

    def __init__(self, area, equipment, name, datatype, unit, writable, command_target):
        self.area = area
        self.equipment = equipment
        self.name = name
        self.datatype = datatype
        self.unit = unit
        self.writable = writable
        self.command_target = command_target

    @property
    def wire_unit(self) -> str:
        return WIRE_UNIT.get(self.unit, self.unit)

    @property
    def node_suffix(self) -> str:
        """The part after `DairyWorks.Vla.` in the OPC-UA NodeId string."""
        if self.area is None:  # line-level Batch object
            return f"Batch.{self.name}"
        return f"{self.area}.{self.equipment}.{self.name}"

    @property
    def topic_suffix(self) -> str:
        """The per-address topic; MonsterMQ prefixes the device namespace."""
        if self.area is None:
            return f"Batch/Status/{self.name}"
        return f"{self.area}/{self.equipment}/Status/{self.name}"


def load_tags(model: dict) -> tuple[list[Tag], list[Tag]]:
    """Return (equipment_tags, batch_tags) in model order.

    Model order is load-bearing: it keeps the generated diffs readable and the
    OPC-UA browse order stable between runs.
    """
    line = model["enterprise"]["sites"][0]["lines"][0]
    equipment: list[Tag] = []
    for area in line["areas"]:
        for wc in area["work_centers"]:
            eq = wc["equipment_id"]
            for t in wc["tags"]:
                tag_eq, tag_name = t["id"].split(":", 1)
                if tag_eq != eq:
                    raise SystemExit(
                        f"model inconsistency: tag id {t['id']!r} does not match "
                        f"equipment_id {eq!r} in work_center {wc['id']!r}"
                    )
                equipment.append(Tag(
                    area=area["name"],
                    equipment=eq,
                    name=tag_name,
                    datatype=t["opcua_datatype"],
                    unit=t["engineering_unit"],
                    writable=bool(t.get("writable")),
                    command_target=t.get("command_target"),
                ))
    batch: list[Tag] = []
    for t in line["batch_object"]["tags"]:
        _, tag_name = t["id"].split(":", 1)
        batch.append(Tag(
            area=None,
            equipment="Batch",
            name=tag_name,
            datatype=t["opcua_datatype"],
            unit=t["engineering_unit"],
            writable=bool(t.get("writable")),
            command_target=t.get("command_target"),
        ))
    return equipment, batch


# ---------------------------------------------------------------------------
# 1. factory/_generated_tags.py: the OPC-UA address space
# ---------------------------------------------------------------------------

def render_factory(equipment: list[Tag]) -> str:
    out: list[str] = [
        '"""AREA_TAGS and SETPOINT_TARGETS for the Vla factory OPC-UA server.',
        "",
    ]
    out += [BANNER, '"""', "from __future__ import annotations", "",
            "from asyncua import ua", "",
            "# (area, equipment) -> [(tag, VariantType, writable), ...]",
            "AREA_TAGS: dict[tuple[str, str], list[tuple[str, ua.VariantType, bool]]] = {"]

    seen: list[tuple[str, str]] = []
    for t in equipment:
        key = (t.area, t.equipment)
        if key not in seen:
            if seen:
                out.append("    ],")
            out.append(f'    ("{t.area}", "{t.equipment}"): [')
            seen.append(key)
        out.append(
            f'        ("{t.name}", ua.VariantType.{VARIANT[t.datatype]}, {t.writable}),'
        )
    if seen:
        out.append("    ],")
    out.append("}")
    out.append("")
    out.append("# writable node -> the SetSetpoint target string it drives")
    out.append("SETPOINT_TARGETS: dict[tuple[str, str, str], str] = {")
    for t in equipment:
        if t.command_target:
            out.append(
                f'    ("{t.area}", "{t.equipment}", "{t.name}"): "{t.command_target}",'
            )
    out.append("}")
    out.append("")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 2. connector/_generated_tags.py: the fallback bridge tables
# ---------------------------------------------------------------------------

def render_connector(equipment: list[Tag], batch: list[Tag]) -> str:
    out = ['"""STATUS_TAGS / BATCH_TAGS / EQUIP_SETPOINT_TARGET for the fallback connector.',
           "", BANNER, '"""', "from __future__ import annotations", "",
           "# (Area, Equipment, tag, unit)",
           "STATUS_TAGS: list[tuple[str, str, str, str]] = ["]
    current = None
    for t in equipment:
        if t.area != current:
            out.append(f"    # {t.area}")
            current = t.area
        out.append(
            f'    ("{t.area}", "{t.equipment}", "{t.name}", "{t.wire_unit}"),'
        )
    out.append("]")
    out.append("")
    out.append("# (tag, unit) on the line-level Batch object")
    out.append("BATCH_TAGS: list[tuple[str, str]] = [")
    for t in batch:
        out.append(f'    ("{t.name}", "{t.wire_unit}"),')
    out.append("]")
    out.append("")
    out.append("# equipment-level Command topic -> SetSetpoint target")
    out.append("# Keyed (Area, Equipment, tag): _route_equipment_command builds")
    out.append("# exactly that 3-tuple from the Command topic segments.")
    out.append("EQUIP_SETPOINT_TARGET: dict[tuple[str, str, str], str] = {")
    for t in equipment:
        if t.command_target:
            out.append(
                f'    ("{t.area}", "{t.equipment}", "{t.name}"): "{t.command_target}",'
            )
    out.append("}")
    out.append("")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 3. monstermq-init/init-vla-opcua.sh: only the TAGS block, between markers
# ---------------------------------------------------------------------------

def render_init_tags(equipment: list[Tag], batch: list[Tag]) -> str:
    lines = [BEGIN, 'TAGS="']
    for t in equipment + batch:
        lines.append(f"{t.node_suffix}|{t.topic_suffix}")
    lines.append('"')
    lines.append(END)
    return "\n".join(lines)


def splice(path: Path, block: str) -> str:
    """Replace the region between BEGIN/END markers, keeping everything else."""
    text = path.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        raise SystemExit(
            f"{path.relative_to(ROOT)} has no generated-block markers. Add:\n"
            f"  {BEGIN}\n  ...\n  {END}"
        )
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return head + block + tail


# ---------------------------------------------------------------------------

def targets(model: dict) -> dict[Path, str]:
    equipment, batch = load_tags(model)
    init_path = ROOT / "monstermq-init" / "init-vla-opcua.sh"
    return {
        ROOT / "factory" / "_generated_tags.py": render_factory(equipment),
        ROOT / "connector" / "_generated_tags.py": render_connector(equipment, batch),
        init_path: splice(init_path, render_init_tags(equipment, batch)),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="fail if a generated file is out of date; write nothing")
    args = ap.parse_args()

    if not MODEL.exists():
        print(f"[gen-connect] model not found: {MODEL}", file=sys.stderr)
        return 2
    model = json.loads(MODEL.read_text(encoding="utf-8"))

    equipment, batch = load_tags(model)
    wanted = targets(model)

    stale: list[str] = []
    for path, content in wanted.items():
        rel = path.relative_to(ROOT)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(str(rel))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"[gen-connect] wrote {rel}")

    if args.check:
        if stale:
            print("[gen-connect] OUT OF DATE: " + ", ".join(stale), file=sys.stderr)
            print("[gen-connect] run: python tools/gen-connect.py", file=sys.stderr)
            return 1
        print(f"[gen-connect] CHECK OK: {len(equipment)} equipment tags + "
              f"{len(batch)} batch tags, {len(wanted)} artefacts in sync")
        return 0

    print(f"[gen-connect] done: {len(equipment)} equipment tags + {len(batch)} "
          f"batch tags -> {len(equipment) + len(batch)} MonsterMQ addresses")
    return 0


if __name__ == "__main__":
    sys.exit(main())
